POST http://localhost:3001/api/movies/
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbUBlbWFpbC5jb20iLCJpZCI6IjYzYzJkMDhjYzVlN2M2YTljZWZlODgwMiIsImlhdCI6MTY3Mzg2NTE1MiwiZXhwIjoxNjczODY4NzUyfQ.kOr5ccnqPgi_CXnmxQy74AGe0G1vSYK9OuZDrmipGFA

{
    "tmdbId": "573171",
    "title": "A Frozen Rooster",
    "overview": "The rooster Toto has a new enemy: a pirate who plans to turn him into a cryogenically frozen rooster.",
    "poster": "/gBBCBMXKzWRADtliUYfV69aVIcz.jpg"    
}

#     
# 