DELETE http://localhost:3001/api/movies/63c6d1cc993dcd23393ccba1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbUBlbWFpbC5jb20iLCJpZCI6IjYzYzJkMDhjYzVlN2M2YTljZWZlODgwMiIsImlhdCI6MTY3NDEyNTAzNiwiZXhwIjoxNjc0MTI4NjM2fQ.7YUZy_KSXxtqG1ogzJQwzLuQ6DzrzECw7Y1ovnPJae0
