DELETE http://localhost:3001/api/movies/63b8589af5fc6d38a7f0acaf
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJpZCI6IjYzYjg1MWIzZDAyYmFmODQzNmM3MTQ3MyIsImlhdCI6MTY3MzA4NjcyMywiZXhwIjoxNjczMDkwMzIzfQ.BxHo2sC0K4d4SK4NAjO4_GotA9RbBYpdDfahfiLbpjI
