GET http://localhost:3001/api/users/63c2d08cc5e7c6a9cefe8802
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRvbUBlbWFpbC5jb20iLCJpZCI6IjYzYzJkMDhjYzVlN2M2YTljZWZlODgwMiIsImlhdCI6MTcxMjY0OTczMCwiZXhwIjoxNzEyNjUzMzMwfQ.EFew8jF5I2JtR2FwYCQap1xHzDu2863aM98v7qHGFKI