GET http://localhost:3001/api/users/63b851b3d02baf8436c71473
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJpZCI6IjYzYjg1MWIzZDAyYmFmODQzNmM3MTQ3MyIsImlhdCI6MTY3MzA4MTUwOSwiZXhwIjoxNjczMDg1MTA5fQ.tTvQ8ERdb6xXLII1gVXQzZXyuFg64aZGqbBUG6_iX1Y