GET http://localhost:3001/api/users/63b851b3d02baf8436c71473
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJpZCI6IjYzYjg1MWIzZDAyYmFmODQzNmM3MTQ3MyIsImlhdCI6MTY3MzA4NDQwNiwiZXhwIjoxNjczMDg4MDA2fQ.PY7GUhm4BG1UW5NQbwRLEqpf8T95MghJUGnJieMJBrI