PUT http://localhost:3001/api/movies/63b8589af5fc6d38a7f0acaf
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAbWFpbC5jb20iLCJpZCI6IjYzYjg1MWIzZDAyYmFmODQzNmM3MTQ3MyIsImlhdCI6MTY3MzA4NDQwNiwiZXhwIjoxNjczMDg4MDA2fQ.PY7GUhm4BG1UW5NQbwRLEqpf8T95MghJUGnJieMJBrI
Content-Type: application/json

{
    "watched": false
}